CREATE TABLE "roles" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(35) NOT NULL
);

CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(35),
  "email" varchar(100) UNIQUE NOT NULL,
  "password" varchar(35) NOT NULL,
  "age" int,
  "role_id" int NOT NULL
);

CREATE TABLE "course_levels" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(20)
);

CREATE TABLE "courses" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(30) NOT NULL,
  "description" varchar(100),
  "level_id" int NOT NULL,
  "teacher_id" int NOT NULL
);

CREATE TABLE "course_videos" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(30) NOT NULL,
  "url" varchar(100) UNIQUE NOT NULL,
  "course_id" int NOT NULL
);

CREATE TABLE "categories" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(35) UNIQUE NOT NULL
);

CREATE TABLE "categories_courses" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "course_id" int NOT NULL,
  "categorie_id" int NOT NULL
);

CREATE TABLE "users_students" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "student_id" int NOT NULL,
  "course_id" int NOT NULL
);

ALTER TABLE "users_students" ADD FOREIGN KEY ("student_id") REFERENCES "users" ("id");

ALTER TABLE "users_students" ADD FOREIGN KEY ("course_id") REFERENCES "courses" ("id");

ALTER TABLE "users" ADD FOREIGN KEY ("role_id") REFERENCES "roles" ("id");

ALTER TABLE "courses" ADD FOREIGN KEY ("teacher_id") REFERENCES "users" ("id");

ALTER TABLE "course_videos" ADD FOREIGN KEY ("course_id") REFERENCES "courses" ("id");

ALTER TABLE "categories_courses" ADD FOREIGN KEY ("categorie_id") REFERENCES "categories" ("id");

ALTER TABLE "categories_courses" ADD FOREIGN KEY ("course_id") REFERENCES "courses" ("id");

ALTER TABLE "courses" ADD FOREIGN KEY ("level_id") REFERENCES "course_levels" ("id");

/* EXAMPLES VALUES */

INSERT INTO roles (name) VALUES ('student'), ('teacher'), ('admin');

INSERT INTO users (name, email, password, age, role_id) VALUES ('Jonathan', 'jona@gmail.com', 'Skate12345', 30, 3), ('Edwin', 'edwin@gmail.com', 'Ed12345', 35, 1), ('Mauricio', 'mao@gmail.com', 'MMLK12345', 32, 2); 

INSERT INTO course_levels (name) VALUES ('Beginner'), ('Intermediate'), ('Advance');

INSERT INTO courses (title, description, level_id, teacher_id) VALUES ('Pyton', 'This course is for students who wants to learn the basics skills for phyton', 1 , 3), ('React', 'This course is for students who wants to improve the skills in React', 2 , 3);

INSERT INTO course_videos (title, url, course_id) VALUES ('Starting in python', 'www.academlo.com/courses/startinginpyton', 1), ('React Intermediate', 'www.academlo.com/courses/ReactInter', 2);

INSERT INTO categories (name) VALUES ('Data Analisys'), ('Frontend'); 

INSERT INTO categories_courses (course_id, categorie_id) VALUES (1, 1), (2, 2);

INSERT INTO users_students (student_id, course_id) VALUES (2, 1), (2, 2);




